### ISSUE TITLE
Graph/Time series panel displays too thick bars when data points are not many

### ISSUE THREAD

**Issue by eduelias** [grafana/timestream-datasource#154] opened 2022-03-24 11:24 UTC
**What happened**:
When using the Time Series panel over Time Stream(Or the old graph panel, on both 8.4.4 and 7.5.4), when having too few data points, the graph bars extends for more than the period they were collected (What represents a 30s interval spans through 2h40m).
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/12836540/159906062-61fc0240-fa00-403e-a4de-18e274880f0a.png">

**What you expected to happen**:
Data points should be displayed on their right time, with bars that are constrained inside their own time spam. If someones wants to see thicker bars, a configuration should be available, allowing bars to "bleed out" from their timespan to X timespans (let's say: I'm willing to see 30s bars span through a whole minute, or 5min, or 10min). If such configuration is not set, the bars should be set inside said timeframe and only expand when zoomed in, as the whole timeframe would also increase in size by the zooming in. 
Using ELK connector the data is displayed on the correct way, but because the ELK connector itself generate empty results to fill in the panel and, by doing this, it achieves the expected result as the image beneath
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12836540/159906184-c06e1120-b423-413d-bde9-edbbcc281037.png">

**How to reproduce it (as minimally and precisely as possible)**:
Add a graph panel querying for two or three points only from time stream. Instead of bars you're going to see irrational big boxes (there is no reason for the bar to be that big).

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 7.5.4 and 8.4.4
- User OS & Browser: Safari and Chrome
- Others: Using Time Stream and ELK.

**Comment by eduelias** [comment] 2022-03-24 15:21
Hi @sarahzinger, thanks for your reply! We've been playing a lot with those configs and, yes, using points is the current solution we're using but as we have a dashboard with at least 30 graph panels with bars, the points can get lost and it's quite hard to really see them through all the panels. 

The No Value simply don't do anything at all.

After all, I believe the panel should work with the given data, right? 

Again thanks for your time and answer! :D

**Comment by eduelias** [comment] 2022-03-25 13:39
@sarahzinger The interval solution works if we put a 12h or 24h interval. This way, the bars will be small enough as they should. But the data won't help us, as we usually works with a single interval through the whole dashboard (30s is our sweet spot). 
We were able to replicate using Time Stream and having at most 3 data points like this: 
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/12836540/160131182-969b0f4b-c395-41d5-8dbe-f373e1a446d7.png">

The points being visible is not about the points itself. It's about the whole dashboard. When full of dots it can get a bit confusing and chaotic. With the bars is, too, a bit confusing (as we have many many different colours and sizes) but it's better to see bars then dots.

Nevertheless, we're adopting the dots while we're trying to find a way to fix the bug with the bars.

**Comment by sarahzinger** [comment] 2022-03-25 18:53
@eduelias maybe can you give us a sample query that you are running? When I run a time series query in the time stream datasource and select 3 data points it does not show the bars over many hours, but maybe we have our data formatted differently somehow?

**Comment by eduelias** [comment] 2022-03-28 08:55
@sarahzinger: 
```SQL 
SELECT  CREATE_TIME_SERIES(t,errors), statusCode FROM ( 
     SELECT  bin(time, 30000ms) as t, statusCode, (SUM(errors) /(1.0*to_milliseconds(30000ms)/30000)) as errors 
     FROM  "db"."table" 
     WHERE time BETWEEN from_milliseconds(timeStart) AND from_milliseconds(timeEnd) 
     AND dimension1 LIKE '%somestring' 
     GROUP BY bin(time, 30000ms),statusCode 
     ORDER BY statusCode, bin(time, 30000ms) 
 ) GROUP BY statusCode
```

The data returned by this query is this:
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/12836540/160362681-d2f3046f-0086-41bf-818a-a1026bbe5a0e.png">

The shown graph is this:

We're using a multi-measure time stream table, with region, dimension1 and statusCode as dimensions and errors as measures.

**Comment by leeoniya** [comment] 2022-03-31 13:34
duplicate of https://github.com/grafana/grafana/issues/14130, right?

**Comment by yaelleC** [comment] 2022-03-31 13:52
Indeed! Thanks @leeoniya

**Comment by eduelias** [comment] 2022-04-04 09:15
@yaelleC We've seen this behaviour with 1,2 or 3 data points. Usually with just one is the worst but, it also happens with 1 or 2 too ...
<img width="966" alt="image" src="https://user-images.githubusercontent.com/12836540/161512821-443bf496-8dca-402a-a362-a8118641b4f1.png">

I believe it has to do with the space between the points. If you add them with a lot of time between the points, the bars will get stretched. Sometimes they overlap, sometimes they don't.

**Comment by eduelias** [comment] 2022-04-05 09:24
@yaelleC First, thanks for your help and effort on this, ok? Second, Is there any timeline when (even if) this solution will be released (or if it'll be released altogether)? Otherwise we'll need to find a different solution for this issue. Again, thanks for your time! :D

**Comment by yaelleC** [comment] 2022-04-06 13:13
Hi @eduelias , looking at your screenshot it looks like this issue appears for 1 datapoint per time serie (`404` and `200` here). 

I'm afraid I don't have a timeline for this issue, it is currently in the backlog of our Business Intelligence squad. 
Tagging @taleena in case she has more info here.

**Comment by taleena** [comment] 2022-04-21 02:17
I recently posted a possible fix in the other ticket that might be worth a shot, and I'm also pinging the BI team.
https://github.com/grafana/grafana/issues/14130#issuecomment-1104636833

**Comment by taleena** [comment] 2022-04-21 16:51
Fix posted in the linked issue, so closing this.

**Closed by taleena** 2022-04-21 16:51 UTC
Labels: datasource/Timestream, type/bug
