### ISSUE TITLE
Unable to view DB tables even though connection successful (AWS Timestream)

### ISSUE THREAD

**Issue by cahmadi477** [grafana/timestream-datasource#30] opened 2020-12-22 17:46 UTC
I am trying to use Grafana to connect and visualize data from AWS Timestream. I am able to connect to Timestream and view all the databases associated with the access/secret key I have provided; however, I cannot see any of the tables within any DB. 

![image](https://user-images.githubusercontent.com/43790955/102917831-e632df00-4453-11eb-9657-81dd0c0b4ce3.png)

**Comment by Darth-Bobo** [comment] 2021-01-06 15:32
Same for me, Grafana v7.3.6 (ea06633c34) and Amazon Timestream plugin 1.1.1.  The plugin seems to be working OK, existing panels still have data and I can run things like "SHOW TABLES FROM $__database" in Explore as long as I manually enter the DB name against the Macro field.

It was working on 7.3.4.

**Comment by mark-lvl** [comment] 2021-01-08 14:23
This been resolved in v1.1.1

**Comment by Darth-Bobo** [comment] 2021-01-08 14:40
Confirmed, everything working again with v1.1.**2**

**Comment by Darth-Bobo** [comment] 2021-01-12 10:50
Correction, the fixed version now places double quotes around $__measure preventing it from being used in queries.  Existing queries seem to be working, but new ones cannot be created.

e.g. This does not work

<img width="1521" alt="Screenshot 2021-01-12 at 10 46 52" src="https://user-images.githubusercontent.com/50400845/104304709-a2b41980-54c3-11eb-99d9-d548d727f114.png">

Neither does using **measure_name = $__measure**, but using **measure_name = 'com_select'** does work.

**Comment by ryantxu** [comment] 2021-02-25 21:57
looks like this is resolved

**Closed by ryantxu** 2021-02-25 21:57 UTC

**Comment by RaistlinD2x-Dev** [comment] 2022-12-11 20:09
I'm having an issue with this. No matter which authorizer I use, when attempting to find Databases for Timestream I'm getting "Bad Gateway error." Looking at dev tools console it shows various 502 and 404 errors around not finding it. I made sure my Grafana is set up in public subnets to all traffic in and out, I even add AdministratorAccess to the Service Managed role created by grafana with no luck. It just errors out when attempting to see Databases.

**Comment by 171aldash** [comment] 2023-11-16 16:49
@RaistlinD2x-Dev  did you manage to resolve the issue in the end? I am having the same issue.
